### ISSUE TITLE
its not supporting with laravel 8

### ISSUE THREAD

**Issue by ajithjojo** [wingsline/laravel-blog#13]
**Describe the bug**
when I install this with Laravel 8, I got an error message `Your requirements could not be resolved to an installable set of packages.`
`Problem 1
    - wingsline/blog[v2.0.0, ..., 2.x-dev] require illuminate/support ~7 -> found illuminate/support[v7.0.0, ..., 7.x-dev] but it conflicts with another require.
    - Root composer.json requires wingsline/blog ^2.0 -> satisfiable by wingsline/blog[v2.0.0, 2.x-dev].`

**To Reproduce**
Just install this package in Laravel 8

**Comment by wingsline** [comment]
The package currently doesn't support L8, will be updated soon to support it.
