### ISSUE TITLE
Admin dashboard doesn't load main.css correctly

### ISSUE THREAD

**Issue by victoragudo** [wingsline/laravel-blog#6]
**Describe the bug**
The admin dashboard doesn't load resources like main.css correctly if the project is it into a subdomain.

**To Reproduce**
1. Install laravel-blog following the steps as normally into some subdomain like http://localhost/subdomain/blog
2. Install theme as normally into the root path
3. Go to admin dashboard and you will see that the resources doesn't load correctly.

**Expected behavior**
The expected behaviour is that show the admin panel with the css files correctly loaded.

**Comment by wingsline** [comment]
I pushed a new version (v1.2.4), this one uses absolute URL's for assets. If still not working let me know. You can also try to publish the views and customize the asset links in the `layouts/master.blade.php` file:

```sh
php artisan vendor:publish --tag blog.views
```

This will place the admin blade views in `resources/views/vendor/wingsline` folder.

**Comment by victoragudo** [comment]
Now the admin dashboard looks like well, but, when you want to push new post, the icons of the editor doesn't show correctly, I think it's because the relative URL inside the main.css.

```
src: url(/vendor/wingsline-blog/fonts/fontawesome-webfont.eot?v=4.7.0);
```
Thanks you so much for the work!

**Comment by wingsline** [comment]
Ok, updated the path to the font, it should work now. Update to v1.2.5 and also re-publish the new assets:

```sh
php artisan blog:publish
```

Let me know it fixed the issue.
